FROM node:24-alpine

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend ./
RUN npm run build

EXPOSE 4200
CMD ["npx", "ng", "serve", "--configuration", "production", "--host", "0.0.0.0", "--port", "4200", "--allowed-hosts", "portal.renner.com.br"]
